### ISSUE TITLE
能否添加一个设置选项, 把侧栏显示转为浮窗显示.

### ISSUE THREAD

**Issue by XMB-7** [gaoxin3220119/SideNote#3]
侧栏显示注释, 有一个大问题是, 一旦添加稍微多的内容, 视觉效果就比较差了.
我更希望能类似hover editor以浮窗的形式来显示, 给每条注释以更大的窗口空间. 不知能否调用hover editor联动实现. 
若方便实现, 就可以让用户自行选择是侧栏显示还是浮窗显示.

**Comment by gaoxin3220119** [comment]
谢谢您的建议。我的想法是搞一个类似康莱尔笔记[ `Cornell Notes system` ](https://zh.wikipedia.org/zh-hans/%E5%BA%B7%E5%A5%88%E5%B0%94%E7%AC%94%E8%AE%B0%E6%B3%95)的笔记插件。要实现hover editor的功能，其实hover editor已经实现了，没有必要在搞一个。

**Comment by XMB-7** [comment]
就我个人体会而言, 侧栏形式的康奈尔笔记系统基本属于鸡肋, 如果写的注释内容少, 完全可以用脚注等实现, 鼠标悬浮即可查看内容, 没必要单独上一个侧栏, 而如果写的注释内容多, 比如1000字, 侧栏显示起来就纯属是灾难. 
康奈尔笔记的侧栏形式是纸质化时代的局限性产物, 对如今电子化的笔记而言反而是鸡肋, 这是我的个人想法, 所以我希望的是基于hover editor来实现一个浮窗形式的康奈尔笔记系统, 而非传统的侧栏形式的.
顺便一提, 其实我觉得康奈尔笔记系统整个都是鸡肋, 是落后时代的, 无论是侧栏形式还是浮窗形式, 比如我要往注释里插入表格图片乃至其它段落的链接, 这些都不支持, 但我目前也没找到最好的笔记注释系统.

**Comment by gaoxin3220119** [comment]
hover editor 不是已经实现了吗？
您的需求是什么呢？能不能画一个图或者什么的，我们探讨一下。
我的理解，您是不是想在点击侧边栏时，可以弹出一个类似于hover editor的窗口？可以跳转、可以编辑什么的？

**Comment by XMB-7** [comment]
我不是指把整个侧栏都转成浮窗显示, 这个hover editor确实已经实现了, 但在我看来好像也确实没多大意义. 我指的是把侧栏里的某条注释单独转成浮窗显示, 比如当其内容很多的时候, 将其从侧栏里拉出来单独用浮窗显示, 就会更加方便浏览以及编辑(还能选择折叠浮窗).

另外我还有个更加不成熟的想法, 相比于使用html标签来囊括注释内容, 能否直接利用md标题来标注注释内容呢. 
假如约定所有第六级标题下的内容都是侧栏注释, 那么往注释里放入链接列表表格图片等等内容就都可行了.
具体形如, 
```
正文段落a...               |    侧栏
###### 注释a               |     ---
注释文本                   |    注释a...
图片                       |    注释b...
列表                       |    (点击其中一条, 弹出浮窗显示对应标题下的所有内容作为注释)
正文段落b...               |    
###### 注释b               |
注释文本                   |
图片                       |
列表                       |
...
```
